// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-k-0Joz7BbYq3lw-Nxfev4h3xSuh9bqo',
    appId: '1:636786936873:web:dbc0e76abbafedc933e038',
    messagingSenderId: '636786936873',
    projectId: 'loginequiporobles-426fa',
    authDomain: 'loginequiporobles-426fa.firebaseapp.com',
    storageBucket: 'loginequiporobles-426fa.firebasestorage.app',
    measurementId: 'G-1QY21TR0SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8U_MHj_aDwbD_uAVy5JarE-W9uwfrVR8',
    appId: '1:636786936873:android:22a14a2c0bd7953b33e038',
    messagingSenderId: '636786936873',
    projectId: 'loginequiporobles-426fa',
    storageBucket: 'loginequiporobles-426fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDalouqINOCgEnZXysXefntz1kiOeppZ2k',
    appId: '1:636786936873:ios:b5ef79a919c937c833e038',
    messagingSenderId: '636786936873',
    projectId: 'loginequiporobles-426fa',
    storageBucket: 'loginequiporobles-426fa.firebasestorage.app',
    iosBundleId: 'com.example.loginEquiporobles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDalouqINOCgEnZXysXefntz1kiOeppZ2k',
    appId: '1:636786936873:ios:b5ef79a919c937c833e038',
    messagingSenderId: '636786936873',
    projectId: 'loginequiporobles-426fa',
    storageBucket: 'loginequiporobles-426fa.firebasestorage.app',
    iosBundleId: 'com.example.loginEquiporobles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-k-0Joz7BbYq3lw-Nxfev4h3xSuh9bqo',
    appId: '1:636786936873:web:7f43ef04321d6c6d33e038',
    messagingSenderId: '636786936873',
    projectId: 'loginequiporobles-426fa',
    authDomain: 'loginequiporobles-426fa.firebaseapp.com',
    storageBucket: 'loginequiporobles-426fa.firebasestorage.app',
    measurementId: 'G-PN5F57793Y',
  );
}
